log    =    log/project-chtc_$(Cluster)_$(Process).log
error  =  error/project-chtc_$(Cluster)_$(Process).err
output = output/project-chtc_$(Cluster)_$(Process).out

executable = ./alg.sh

arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R412.tar.gz, packages.tar.gz, data.R, $(file).R, train_sample.csv

request_cpus = 7
request_memory = 500GB
request_disk = 500GB

queue file from files.txt
